name: build-icon

on:
  - push

jobs:
  build-icon:
    name: build icon
    strategy:
      matrix:
        node:
          - 14
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - name: Update UI catalog
        env:
          FILE_KEY: ${{ secrets.FIGMA_ICON_FILE_KEY }}
          NODE_ID: ${{ secrets.FIGMA_ICON_NODE_ID }}
          ICON_NAMES: clock
        run: |
          echo '{ "fileKey": "$FILE_KEY", "nodeId": "$NODE_ID", "dest": "dist", "iconNames": "$ICON_NAMES" }' > packages/spindle-icons/figma.json
          cat packages/spindle-icons/figma.json
