name: testpr

on:
  push:
    branches:
      - test/pr

jobs:
  pr:
    name: testpr
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ github.token }}" \
            https://api.github.com/repos/${{ github.event.repository.owner.name }}/${{ github.event.repository.name }}/pulls \
            -d '{"head":"test/pr","base":"${{ github.event.repository.default_branch }}","title":"PR"}'
        env:
          GH_TOKEN: ${{ github.token }}
